/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package final_project;

import java.awt.Color;
import java.util.*;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author kevinsanchez
 */
public class JFrameAccount extends javax.swing.JFrame {

    /**
     * Creates new form JFrameAccount
     */

    public JFrameAccount() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonChurro = new javax.swing.JButton();
        jButtonMc = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonPollo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jButtonClose = new javax.swing.JButton();
        jButtonLogOut = new javax.swing.JButton();
        jTextFieldPhone = new javax.swing.JTextField();
        jTextFieldCarNum = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        jTextFieldCardExpiration = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jButtonChurro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/ChurroImages/ChurroLogo2.jpeg"))); // NOI18N
        jButtonChurro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChurroActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonChurro);
        jButtonChurro.setBounds(350, 260, 110, 90);

        jButtonMc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/McImages/Mclogo.jpeg"))); // NOI18N
        jButtonMc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMcActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMc);
        jButtonMc.setBounds(610, 260, 110, 90);

        jLabel9.setText("Credit/Debit card expiration date:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 350, 220, 20);

        jButtonPollo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/PolloImages/logo.jpeg"))); // NOI18N
        jButtonPollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPolloActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPollo);
        jButtonPollo.setBounds(480, 260, 110, 90);

        jLabel8.setText("Where you want to order today?");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(310, 230, 250, 16);

        jLabel7.setText("More restaurants coming soon ...");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(320, 390, 210, 20);

        jLabel6.setText("Please fill your information before making an order");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 170, 340, 40);

        jLabel2.setFont(new java.awt.Font("Chalkduster", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("My OrderD");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 0, 360, 110);

        jLabel3.setText("Address:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 170, 80, 20);

        jLabel4.setText("Phone number:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 230, 100, 20);

        jLabel5.setText("Credit/Debit card number:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 290, 170, 20);

        jTextFieldName.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(jTextFieldName);
        jTextFieldName.setBounds(10, 130, 260, 26);

        jButtonClose.setBackground(new java.awt.Color(153, 255, 153));
        jButtonClose.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jButtonClose.setForeground(new java.awt.Color(0, 153, 51));
        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClose);
        jButtonClose.setBounds(0, 450, 85, 29);

        jButtonLogOut.setBackground(new java.awt.Color(153, 255, 153));
        jButtonLogOut.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jButtonLogOut.setForeground(new java.awt.Color(0, 153, 51));
        jButtonLogOut.setText("Log out");
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogOut);
        jButtonLogOut.setBounds(180, 450, 100, 29);

        jTextFieldPhone.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(jTextFieldPhone);
        jTextFieldPhone.setBounds(10, 250, 260, 26);

        jTextFieldCarNum.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(jTextFieldCarNum);
        jTextFieldCarNum.setBounds(10, 310, 260, 26);

        jTextFieldAddress.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(jTextFieldAddress);
        jTextFieldAddress.setBounds(10, 190, 260, 26);

        jTextFieldCardExpiration.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(jTextFieldCardExpiration);
        jTextFieldCardExpiration.setBounds(10, 370, 260, 26);

        jLabel10.setText("Name:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 110, 40, 16);

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));

        jButtonSave.setBackground(new java.awt.Color(153, 255, 153));
        jButtonSave.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jButtonSave.setForeground(new java.awt.Color(0, 153, 51));
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jButtonSave)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addComponent(jButtonSave)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 110, 300, 330);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/Background2.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 0, 730, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPolloActionPerformed
        // TODO add your handling code here:
        JFramePolloTropical frameP = new JFramePolloTropical();
        frameP.show();
        dispose();
    }//GEN-LAST:event_jButtonPolloActionPerformed

    private void jButtonChurroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChurroActionPerformed
        // TODO add your handling code here:
        JFrameChurromania frameC = new JFrameChurromania();
        frameC.show();
        dispose();
    }//GEN-LAST:event_jButtonChurroActionPerformed

    private void jButtonMcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMcActionPerformed
        // TODO add your handling code here:
        JFrameMcDonalds frameM = new JFrameMcDonalds();
        frameM.show();
        dispose();
    }//GEN-LAST:event_jButtonMcActionPerformed

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        // TODO add your handling code here:
        JFrameFrontPage frameF = new JFrameFrontPage();
        frameF.show();
        dispose();
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Good bye", "Closing" ,JOptionPane.PLAIN_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        String name = jTextFieldName.getText();
        String address = jTextFieldAddress.getText();
        String phone = jTextFieldPhone.getText();
        String cardnum = jTextFieldCarNum.getText();
        String cardex = jTextFieldCardExpiration.getText();
        
        try{
            FileWriter fileWriter = new FileWriter("OrderData.txt",true);
            fileWriter.write(name + ";" + address + ";" + phone + ";" + cardnum + ";" + cardex + "\n");
            fileWriter.close();
            JOptionPane.showMessageDialog(null, "Your information has been save", "Congratulations" ,JOptionPane.INFORMATION_MESSAGE); 
            }
        catch(Exception f){
            System.out.println("Error");   
            } 
        
        //new JFrameMcDonalds(nameA, emailA, addressA, phoneA, cardnumA);
        //new JFrameMcDonalds(nameA, emailA, addressA, phoneA, cardnumA);
        
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChurro;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JButton jButtonMc;
    private javax.swing.JButton jButtonPollo;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldCarNum;
    private javax.swing.JTextField jTextFieldCardExpiration;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables
}
