/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package final_project;

import java.awt.Color;
import java.util.*;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author kevinsanchez
 */
public class JFrameMcDonalds extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMcDonalds
     */
    String nameF;
    String phoneF;
    String addressF;
    String cardnumF;
    String cardexF;

    public JFrameMcDonalds() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonClose = new javax.swing.JButton();
        jButtonGoBack = new javax.swing.JButton();
        jButtonMakeOrder = new javax.swing.JButton();
        jRadioButtonPickUp = new javax.swing.JRadioButton();
        jRadioButtonDelivery = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSpinnerNuggets = new javax.swing.JSpinner();
        jSpinnerFries = new javax.swing.JSpinner();
        jSpinnerChickenSandwich = new javax.swing.JSpinner();
        jSpinnerHappymeal = new javax.swing.JSpinner();
        jSpinnerFanta = new javax.swing.JSpinner();
        jSpinnerMcmuffin = new javax.swing.JSpinner();
        jSpinnerCheeseburger = new javax.swing.JSpinner();
        jSpinnerDQpounder = new javax.swing.JSpinner();
        jSpinnerSprite = new javax.swing.JSpinner();
        jSpinnerBiscuit = new javax.swing.JSpinner();
        jSpinnerBigmac = new javax.swing.JSpinner();
        jSpinnerQpounder = new javax.swing.JSpinner();
        jSpinnerCoke = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jButtonClose.setBackground(new java.awt.Color(153, 255, 153));
        jButtonClose.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jButtonClose.setForeground(new java.awt.Color(0, 153, 51));
        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jButtonGoBack.setBackground(new java.awt.Color(153, 255, 153));
        jButtonGoBack.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jButtonGoBack.setForeground(new java.awt.Color(0, 153, 51));
        jButtonGoBack.setText("Go back");
        jButtonGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoBackActionPerformed(evt);
            }
        });

        jButtonMakeOrder.setBackground(new java.awt.Color(153, 255, 153));
        jButtonMakeOrder.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jButtonMakeOrder.setForeground(new java.awt.Color(0, 153, 51));
        jButtonMakeOrder.setText("Make OrderD");
        jButtonMakeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMakeOrderActionPerformed(evt);
            }
        });

        jRadioButtonPickUp.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jRadioButtonPickUp.setForeground(new java.awt.Color(0, 153, 51));
        jRadioButtonPickUp.setText("Pick up");
        jRadioButtonPickUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPickUpActionPerformed(evt);
            }
        });

        jRadioButtonDelivery.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jRadioButtonDelivery.setForeground(new java.awt.Color(0, 153, 51));
        jRadioButtonDelivery.setText("Delivery");
        jRadioButtonDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDeliveryActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/McImages/Mctitle.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/McImages/McBacon,Egg&CheeseBiscuit.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/McImages/McBigMac.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/McImages/McQuarterPounder.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/McImages/Coca-Cola.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/McImages/McEggMcMuffin.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/McImages/McCheeseburger.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/McImages/McDoubleQuarterPounder.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/McImages/Sprite.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/McImages/McFries.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/McImages/McCrispyChickenSandwich.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/McImages/McHamburgerHappyMeal(apples,milk,fries,cheeseburger).png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/McImages/FantaOrange.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/McImages/McChickenMcNuggets.png"))); // NOI18N

        jLabel15.setText("Bacon Egg Cheese Biscuit $4.99");

        jLabel16.setText("Big Mac $5.79");

        jLabel17.setText("Egg McMuffin $4.99");

        jLabel18.setText("Cheeseburger $2.09");

        jLabel19.setText("Crispy Chicken Sandwich $5.19");

        jLabel20.setText("Quater Pounder $6.09");

        jLabel21.setText("Double Quater Pounder $8.09");

        jLabel22.setText("French Fries $2.59");

        jLabel23.setText("Hamburger-Happy Meal $5.69");

        jLabel24.setText("20 McNuggets $8.69");

        jLabel25.setText("Fanta Orange $1.19");

        jLabel26.setText("Sprite $1.19");

        jLabel27.setText("Coke $1.19");

        jLabel28.setText("Name:");

        jLabel29.setText("Phone:");

        jTextFieldName.setBackground(new java.awt.Color(153, 255, 153));

        jTextFieldPhone.setBackground(new java.awt.Color(153, 255, 153));

        jLabel30.setText("Please confirm some data ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(jSpinnerBiscuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(jSpinnerBigmac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(jSpinnerCheeseburger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel11)
                        .addGap(6, 6, 6)
                        .addComponent(jSpinnerChickenSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel16)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel18)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(jSpinnerQpounder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel8)
                        .addGap(6, 6, 6)
                        .addComponent(jSpinnerDQpounder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6)
                        .addComponent(jSpinnerHappymeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel10)
                        .addGap(6, 6, 6)
                        .addComponent(jSpinnerFries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel14)
                        .addGap(6, 6, 6)
                        .addComponent(jSpinnerNuggets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel20)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel24))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addComponent(jSpinnerCoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addComponent(jSpinnerSprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13)
                        .addGap(6, 6, 6)
                        .addComponent(jSpinnerFanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel27)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel26)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel6)
                                .addGap(13, 13, 13)
                                .addComponent(jSpinnerMcmuffin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(jLabel30))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(jLabel28)
                                .addGap(6, 6, 6)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(jLabel29)
                                .addGap(6, 6, 6)
                                .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonGoBack)
                        .addGap(589, 589, 589)
                        .addComponent(jRadioButtonPickUp)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButtonDelivery))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonClose)
                        .addGap(653, 653, 653)
                        .addComponent(jButtonMakeOrder)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jSpinnerBiscuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jSpinnerBigmac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jSpinnerCheeseburger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jSpinnerChickenSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jSpinnerQpounder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jSpinnerDQpounder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12)
                    .addComponent(jSpinnerHappymeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jSpinnerFries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jSpinnerNuggets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22)
                    .addComponent(jLabel24))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jSpinnerCoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jSpinnerSprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jSpinnerFanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jSpinnerMcmuffin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel30)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel28))
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel29))
                            .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGoBack)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonPickUp)
                            .addComponent(jRadioButtonDelivery))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonClose)
                    .addComponent(jButtonMakeOrder)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoBackActionPerformed
        // TODO add your handling code here:
        JFrameAccount frameA = new JFrameAccount();
        frameA.show();
        dispose();
    }//GEN-LAST:event_jButtonGoBackActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Good bye", "Closing" ,JOptionPane.PLAIN_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonMakeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMakeOrderActionPerformed
        // TODO add your handling code here:
        try{
           
        double biscuit = (int)jSpinnerBiscuit.getValue() * 4.99;
        double bigmac = (int)jSpinnerBigmac.getValue() * 5.79;
        double cheeseburger = (int)jSpinnerCheeseburger.getValue() * 2.09;
        double chickensandwich = (int)jSpinnerChickenSandwich.getValue() * 5.19;
        double qpounder = (int)jSpinnerQpounder.getValue() * 6.09;
        double dqpounder = (int)jSpinnerDQpounder.getValue() * 8.09;
        double happymeal = (int)jSpinnerHappymeal.getValue() * 5.69;
        double fries = (int)jSpinnerFries.getValue() * 2.59;
        double nuggets = (int)jSpinnerNuggets.getValue() * 8.69;
        double coke = (int)jSpinnerCoke.getValue() * 1.19;
        double sprite = (int)jSpinnerSprite.getValue() * 1.19;
        double fanta = (int)jSpinnerFanta.getValue() * 1.19;
        double mcmuffin = (int)jSpinnerMcmuffin.getValue() * 4.99;
        double total = 0;
        double totaltax = 0;
        double salestax = 0;
        String name = jTextFieldName.getText();
        String phone = jTextFieldPhone.getText();
        
        Random Order = new Random();
        int ordernum = 99999999 + Order.nextInt(99999999);
       
        File file = new File("OrderData.txt");
 
            Scanner scanner = new Scanner(file);
            while(scanner.hasNextLine()){
                String line = scanner.nextLine();
                String [] componets = line.split(";");
                String nameData = componets[0];
                String addressData = componets[1];
                String phoneData = componets[2];
                String cardnumData = componets[3];
                String cardexData = componets[4];
                
                if(nameData.equals(name) && phoneData.equals(phone)){
                    nameF = nameData;
                    phoneF = phoneData;
                    addressF = addressData;
                    cardnumF = cardnumData;
                    cardexF = cardexData;
                }
            }
      
           FileWriter fileWriter = new FileWriter("Receipt.txt");
           if(jRadioButtonDelivery.isSelected()){
               fileWriter.write("Thank you for shopping at McDonald's " + nameF + "\n" +
                    "- Your order will be sent to your address: "+ addressF + "\n" + 
                    "- Your order number is #" + ordernum + "\n" + 
                    "- Your debit/credit card used was **** **** **** " + cardnumF.substring(cardnumF.length()-4) + "\n" +
                    "- If there is any problem we will call you on your phone " + phoneF + "\n" + "\n");
           } else{
               fileWriter.write("Thank you for shopping at McDonald's " + nameF + "\n" +
                    "- Your order will be ready to pick up on the closest restaurant to your address: " + addressF + "\n" +
                    "- Your order number is #" + ordernum + "\n" + 
                    "- Your debit/credit card used was **** **** **** " + cardnumF.substring(cardnumF.length()-4) + "\n" +
                    "- If there is any problem we will call you on your phone " + phoneF + "\n" + "\n");
           }
        
        if(biscuit>0){
            String biscuitF = String.format("%.2f", biscuit);
            fileWriter.write(jSpinnerBiscuit.getValue() + " Biscuit: $" + biscuitF + "\n");
            total += biscuit;        
        }
        if(bigmac>0){
            String bigmacF = String.format("%.2f", bigmac);
            fileWriter.write(jSpinnerBigmac.getValue() + " Bigmac: $" + bigmacF + "\n");
            total += bigmac;
        }
        if(cheeseburger>0){
            String cheeseburgerF = String.format("%.2f", cheeseburger);
            fileWriter.write(jSpinnerCheeseburger.getValue() + " Cheeseburger: $" + cheeseburgerF + "\n");
            total += cheeseburger;
        }
        if(chickensandwich>0){
            String chickensandwichF = String.format("%.2f", chickensandwich);
            fileWriter.write(jSpinnerChickenSandwich.getValue() + " Chicken Sandwich: $" + chickensandwichF + "\n");
            total += chickensandwich;
        }
        if(qpounder>0){
            String qpounderF = String.format("%.2f", qpounder);
            fileWriter.write(jSpinnerQpounder.getValue() + " Quarter Pounder: $" + qpounderF + "\n");
            total += qpounder;
        }
        if(dqpounder>0){
            String dqpounderF = String.format("%.2f", dqpounder);
            fileWriter.write(jSpinnerDQpounder.getValue() + " Double Quarter Pounder: $" + dqpounderF + "\n");
            total += dqpounder;
        }
        if(happymeal>0){
            String happymealF = String.format("%.2f", happymeal);
            fileWriter.write(jSpinnerHappymeal.getValue() + " Hamburger-Happymeal: $" + happymealF + "\n");
            total += happymeal;
        }
        if(fries>0){
            String friesF = String.format("%.2f", fries);
            fileWriter.write(jSpinnerFries.getValue() + " Fries: $" + friesF + "\n");
            total += fries;
        }
        if(nuggets>0){
            String nuggetsF = String.format("%.2f", nuggets);
            fileWriter.write(jSpinnerNuggets.getValue() + " 20 Nuggets: $" + nuggetsF + "\n");
            total += nuggets;
        }
        if(coke>0){
            String cokeF = String.format("%.2f", coke);
            fileWriter.write(jSpinnerCoke.getValue() + " Coke: $" + cokeF + "\n");
            total += coke;
        }
        if(sprite>0){
            String spriteF = String.format("%.2f", sprite);
            fileWriter.write(jSpinnerSprite.getValue() + " Sprite: $" + spriteF + "\n");
            total += sprite;
        }
        if(fanta>0){
            String fantaF = String.format("%.2f", fanta);
            fileWriter.write(jSpinnerFanta.getValue() + " Fanta: $" + fantaF + "\n");
            total += fanta;
        }
        if(mcmuffin>0){
            String mcmuffinF = String.format("%.2f", mcmuffin);
            fileWriter.write(jSpinnerMcmuffin.getValue() + " McMuffin: $" + mcmuffinF + "\n");
            total += mcmuffin;
        }
        if(total>0){
            fileWriter.write("\n");
            String totalF = String.format("%.2f", total);
            fileWriter.write("Order Total: $" + totalF + "\n");
            
            salestax = total*0.07;
            String salestaxF = String.format("%.2f", salestax);
            fileWriter.write("Sales Tax: $" + salestaxF +"\n");
            
            if(jRadioButtonDelivery.isSelected()){
                totaltax = total + (total * 0.07) + 7.99;
                String totaltaxF = String.format("%.2f", totaltax);
                fileWriter.write("Delivery Fee: +$" + 7.99 + "\n");
                fileWriter.write("Final Total: $" + totaltaxF + "\n");
            } else{
                totaltax = total + (total * 0.07);
                String totaltaxF = String.format("%.2f", totaltax);
                fileWriter.write("Final Total: $" + totaltaxF + "\n");
            }
            
        }
        fileWriter.close();
        JOptionPane.showMessageDialog(null, "Your order is done, check your receipt", "Congratulations" ,JOptionPane.INFORMATION_MESSAGE);
            }
        catch(Exception f){
            JOptionPane.showMessageDialog(null, "Invalid Data!", "System Error" ,JOptionPane.ERROR_MESSAGE);  
        } 
    }//GEN-LAST:event_jButtonMakeOrderActionPerformed

    private void jRadioButtonPickUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPickUpActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonPickUp.isSelected()){
            jRadioButtonDelivery.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonPickUpActionPerformed

    private void jRadioButtonDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDeliveryActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonDelivery.isSelected()){
            jRadioButtonPickUp.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonDeliveryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMcDonalds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMcDonalds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMcDonalds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMcDonalds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMcDonalds().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonGoBack;
    private javax.swing.JButton jButtonMakeOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButtonDelivery;
    private javax.swing.JRadioButton jRadioButtonPickUp;
    private javax.swing.JSpinner jSpinnerBigmac;
    private javax.swing.JSpinner jSpinnerBiscuit;
    private javax.swing.JSpinner jSpinnerCheeseburger;
    private javax.swing.JSpinner jSpinnerChickenSandwich;
    private javax.swing.JSpinner jSpinnerCoke;
    private javax.swing.JSpinner jSpinnerDQpounder;
    private javax.swing.JSpinner jSpinnerFanta;
    private javax.swing.JSpinner jSpinnerFries;
    private javax.swing.JSpinner jSpinnerHappymeal;
    private javax.swing.JSpinner jSpinnerMcmuffin;
    private javax.swing.JSpinner jSpinnerNuggets;
    private javax.swing.JSpinner jSpinnerQpounder;
    private javax.swing.JSpinner jSpinnerSprite;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables
}
