/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package final_project;

import java.awt.Color;
import java.util.*;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author kevinsanchez
 */
public class JFrameChurromania extends javax.swing.JFrame {

    /**
     * Creates new form JFrameChurromania
     */
    String nameF;
    String phoneF;
    String addressF;
    String cardnumF;
    String cardexF;
    
    public JFrameChurromania() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonPickUp = new javax.swing.JRadioButton();
        jSpinnerBiteF = new javax.swing.JSpinner();
        jSpinnerSundae = new javax.swing.JSpinner();
        jSpinnerTwist = new javax.swing.JSpinner();
        jSpinnerFanta = new javax.swing.JSpinner();
        jSpinnerChurrodog = new javax.swing.JSpinner();
        jSpinnerCrispymania = new javax.swing.JSpinner();
        jSpinnerCoffee = new javax.swing.JSpinner();
        jRadioButtonDelivery = new javax.swing.JRadioButton();
        jSpinnerSprite = new javax.swing.JSpinner();
        jSpinnerBigmania = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerBitesC = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpinnerChocolate = new javax.swing.JSpinner();
        jSpinnerCoke = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSpinnerIcecream = new javax.swing.JSpinner();
        jButtonClose = new javax.swing.JButton();
        jButtonGoBack = new javax.swing.JButton();
        jButtonMakeOrder = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jRadioButtonPickUp.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jRadioButtonPickUp.setForeground(new java.awt.Color(0, 153, 51));
        jRadioButtonPickUp.setText("Pick up");
        jRadioButtonPickUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPickUpActionPerformed(evt);
            }
        });

        jRadioButtonDelivery.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jRadioButtonDelivery.setForeground(new java.awt.Color(0, 153, 51));
        jRadioButtonDelivery.setText("Delivery");
        jRadioButtonDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDeliveryActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/ChurroImages/title.jpeg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/ChurroImages/ChurroChurrobitesCrispy.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/ChurroImages/ChurroHotChocolate.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/ChurroImages/Coca-Cola.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/ChurroImages/ChurroChurroDog.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/ChurroImages/ChurroCrispyMania.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/ChurroImages/ChurroHotCoffee.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/ChurroImages/Sprite.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/ChurroImages/ChurroChurrosbitesRellenos.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/ChurroImages/ChurroCrispySundae.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/ChurroImages/ChurroTwistMania.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/ChurroImages/FantaOrange.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/ChurroImages/ChurroChurromaniaIceCream.png"))); // NOI18N

        jButtonClose.setBackground(new java.awt.Color(153, 255, 153));
        jButtonClose.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jButtonClose.setForeground(new java.awt.Color(0, 153, 51));
        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jButtonGoBack.setBackground(new java.awt.Color(153, 255, 153));
        jButtonGoBack.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jButtonGoBack.setForeground(new java.awt.Color(0, 153, 51));
        jButtonGoBack.setText("Go back");
        jButtonGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoBackActionPerformed(evt);
            }
        });

        jButtonMakeOrder.setBackground(new java.awt.Color(153, 255, 153));
        jButtonMakeOrder.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jButtonMakeOrder.setForeground(new java.awt.Color(0, 153, 51));
        jButtonMakeOrder.setText("Make OrderD");
        jButtonMakeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMakeOrderActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/ChurroImages/ChurroBigMania.png"))); // NOI18N

        jLabel2.setText("CrispyMania $12.99");

        jLabel16.setText("BigMania $10.39");

        jLabel17.setText("ChurroBites Filled $14.99");

        jLabel18.setText("ChurroBites Crispy $12.99");

        jLabel19.setText("Hot Chocolate $2.99");

        jLabel20.setText("Hot Coffee $2.99");

        jLabel21.setText("TwistMania $12.99");

        jLabel22.setText("Churro IceCream $4.99");

        jLabel23.setText("Crispy Sundae $9.99");

        jLabel24.setText("Churrodog $15.98");

        jLabel25.setText("Coke $1.19");

        jLabel26.setText("Sprite $1.19");

        jLabel27.setText("Fanta Orange $1.19");

        jLabel30.setText("Please confirm some data ");

        jLabel28.setText("Name:");

        jTextFieldName.setBackground(new java.awt.Color(153, 255, 153));

        jTextFieldPhone.setBackground(new java.awt.Color(153, 255, 153));

        jLabel29.setText("Phone:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(jLabel15)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerBigmania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(jLabel16))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerBitesC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerCrispymania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel10)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerBiteF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel18)
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addComponent(jLabel17))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel12)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerTwist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel14)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerIcecream, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel11)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerSundae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel19)
                .addGap(29, 29, 29)
                .addComponent(jLabel20)
                .addGap(57, 57, 57)
                .addComponent(jLabel21)
                .addGap(51, 51, 51)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jLabel23))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerCoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel9)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerSprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel13)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerFanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel25)
                .addGap(93, 93, 93)
                .addComponent(jLabel26)
                .addGap(92, 92, 92)
                .addComponent(jLabel27))
            .addGroup(layout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerChurrodog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonGoBack)
                .addGap(263, 263, 263)
                .addComponent(jLabel24)
                .addGap(202, 202, 202)
                .addComponent(jRadioButtonPickUp)
                .addGap(6, 6, 6)
                .addComponent(jRadioButtonDelivery))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonClose)
                .addGap(637, 637, 637)
                .addComponent(jButtonMakeOrder))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jSpinnerBigmania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel16)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jSpinnerBitesC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jSpinnerCrispymania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jSpinnerBiteF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel2)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jSpinnerCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jSpinnerTwist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jSpinnerIcecream, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jSpinnerSundae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jSpinnerChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jSpinnerFanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jSpinnerCoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jSpinnerSprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jSpinnerChurrodog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGoBack)
                    .addComponent(jLabel24)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonPickUp)
                            .addComponent(jRadioButtonDelivery))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonClose)
                    .addComponent(jButtonMakeOrder)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoBackActionPerformed
        // TODO add your handling code here:
        JFrameAccount frameA = new JFrameAccount();
        frameA.show();
        dispose();
    }//GEN-LAST:event_jButtonGoBackActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonMakeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMakeOrderActionPerformed
        // TODO add your handling code here:
        try{

        double bigmania = (int)jSpinnerBigmania.getValue() * 10.39;
        double bitesc = (int)jSpinnerBitesC.getValue() * 12.99;
        double crispymania = (int)jSpinnerCrispymania.getValue() * 12.99;
        double bitesf = (int)jSpinnerBiteF.getValue() * 14.99;
        double chocolate = (int)jSpinnerChocolate.getValue() * 2.99;
        double coffee = (int)jSpinnerCoffee.getValue() * 2.99;
        double twist = (int)jSpinnerTwist.getValue() * 12.99;
        double icecream = (int)jSpinnerIcecream.getValue() * 4.99;
        double sundae = (int)jSpinnerSundae.getValue() * 9.99;
        double coke = (int)jSpinnerCoke.getValue() * 1.19;
        double sprite = (int)jSpinnerSprite.getValue() * 1.19;
        double fanta = (int)jSpinnerFanta.getValue() * 1.19;
        double churrodog = (int)jSpinnerChurrodog.getValue() * 15.98;
        double total = 0;
        double totaltax = 0;
        double salestax = 0;
        String name = jTextFieldName.getText();
        String phone = jTextFieldPhone.getText();
        
        Random Order = new Random();
        int ordernum = 99999999 + Order.nextInt(99999999);
        
        File file = new File("OrderData.txt");

            Scanner scanner = new Scanner(file);
            while(scanner.hasNextLine()){
                String line = scanner.nextLine();
                String [] componets = line.split(";");
                String nameData = componets[0];
                String addressData = componets[1];
                String phoneData = componets[2];
                String cardnumData = componets[3];
                String cardexData = componets[4];
                
                if(nameData.equals(name) && phoneData.equals(phone)){
                    nameF = nameData;
                    phoneF = phoneData;
                    addressF = addressData;
                    cardnumF = cardnumData;
                    cardexF = cardexData;
                }
            }
           FileWriter fileWriter = new FileWriter("Receipt.txt");
           if(jRadioButtonDelivery.isSelected()){
               fileWriter.write("Thank you for shopping at Churromania " + nameF + "\n" +
                    "- Your order will be sent to your address: "+ addressF + "\n" + 
                    "- Your order number is #" + ordernum + "\n" + 
                    "- Your debit/credit card used was **** **** **** " + cardnumF.substring(cardnumF.length()-4) + "\n" +
                    "- If there is any problem we will call you on your phone " + phoneF + "\n" + "\n");
           } else{
               fileWriter.write("Thank you for shopping at Churromania \n" + nameF +
                    "- Your order will be ready to pick up on the closest restaurant to your address: " + addressF + "\n" +
                    "- Your order number is #" + ordernum + "\n" + 
                    "- Your debit/credit card used was **** **** **** " + cardnumF.substring(cardnumF.length()-4) + "\n" +
                    "- If there is any problem we will call you on your phone " + phoneF + "\n" + "\n");
           }
           
        if(bigmania>0){
            String bigmaniaF = String.format("%.2f", bigmania);
            fileWriter.write(jSpinnerBigmania.getValue() + " BigMania: $" + bigmaniaF + "\n");
            total += bigmania;
        }
        if(bitesc>0){
            String bitescF = String.format("%.2f", bitesc);
            fileWriter.write(jSpinnerBitesC.getValue() + " ChurroBites Crispy: $" + bitescF + "\n");
            total += bitesc;
        }
        if(crispymania>0){
            String crispymaniaF = String.format("%.2f", crispymania);
            fileWriter.write(jSpinnerCrispymania.getValue() + " CrispyMania: $" + crispymaniaF + "\n");
            total += crispymania;
        }
        if(bitesf>0){
            String bitesfF = String.format("%.2f", bitesf);
            fileWriter.write(jSpinnerBiteF.getValue() + " ChurroBites Filled: $" + bitesfF + "\n");
            total += bitesf;
        }
        if(chocolate>0){
            String chocolateF = String.format("%.2f", chocolate);
            fileWriter.write(jSpinnerChocolate.getValue() + " Hot Chocolater: $" + chocolateF + "\n");
            total += chocolate;
        }
        if(coffee>0){
            String coffeeF = String.format("%.2f", coffee);
            fileWriter.write(jSpinnerCoffee.getValue() + " Hot Coffee: $" + coffeeF + "\n");
            total += coffee;
        }
        if(twist>0){
            String twistF = String.format("%.2f", twist);
            fileWriter.write(jSpinnerTwist.getValue() + " TwistMania: $" + twistF + "\n");
            total += twist;
        }
        if(icecream>0){
            String icecreamF = String.format("%.2f", icecream);
            fileWriter.write(jSpinnerIcecream.getValue() + " Churromania Icecream: $" + icecreamF + "\n");
            total += icecream;
        }
        if(sundae>0){
            String sundaeF = String.format("%.2f", sundae);
            fileWriter.write(jSpinnerSundae.getValue() + " CrispySundae: $" + sundaeF + "\n");
            total += sundae;
        }
        if(coke>0){
            String cokeF = String.format("%.2f", coke);
            fileWriter.write(jSpinnerCoke.getValue() + " Coke: $" + cokeF + "\n");
            total += coke;
        }
        if(sprite>0){
            String spriteF = String.format("%.2f", sprite);
            fileWriter.write(jSpinnerSprite.getValue() + " Sprite: $" + spriteF + "\n");
            total += sprite;
        }
        if(fanta>0){
            String fantaF = String.format("%.2f", fanta);
            fileWriter.write(jSpinnerFanta.getValue() + " Fanta: $" + fantaF + "\n");
            total += fanta;
        }
        if(churrodog>0){
            String churrodogF = String.format("%.2f", churrodog);
            fileWriter.write(jSpinnerChurrodog.getValue() + " ChurroDog: $" + churrodogF + "\n");
            total += churrodog;
        }
        if(total>0){
            fileWriter.write("\n");
            String totalF = String.format("%.2f", total);
            fileWriter.write("Order Total: $" + totalF + "\n");
            
            salestax = total*0.07;
            String salestaxF = String.format("%.2f", salestax);
            fileWriter.write("Sales Tax: $" + salestaxF + "\n");
            
            if(jRadioButtonDelivery.isSelected()){
                totaltax = total + (total * 0.07) + 7.99;
                String totaltaxF = String.format("%.2f", totaltax);
                fileWriter.write("Delivery Fee: +$" + 7.99 + "\n");
                fileWriter.write("Final Total: $" + totaltaxF + "\n");
            } else{
                totaltax = total + (total * 0.07);
                String totaltaxF = String.format("%.2f", totaltax);
                fileWriter.write("Final Total: $" + totaltaxF + "\n");
            }
        }
        fileWriter.close();
        JOptionPane.showMessageDialog(null, "Your order is done, check your receipt", "Congratulations" ,JOptionPane.INFORMATION_MESSAGE);
            }
        
        catch(Exception f){
            JOptionPane.showMessageDialog(null, "Invalid Data!", "System Error" ,JOptionPane.ERROR_MESSAGE);    
            } 
        dispose();
    }//GEN-LAST:event_jButtonMakeOrderActionPerformed

    private void jRadioButtonDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDeliveryActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonDelivery.isSelected()){
            jRadioButtonPickUp.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonDeliveryActionPerformed

    private void jRadioButtonPickUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPickUpActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonPickUp.isSelected()){
            jRadioButtonDelivery.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonPickUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameChurromania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameChurromania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameChurromania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameChurromania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameChurromania().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonGoBack;
    private javax.swing.JButton jButtonMakeOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButtonDelivery;
    private javax.swing.JRadioButton jRadioButtonPickUp;
    private javax.swing.JSpinner jSpinnerBigmania;
    private javax.swing.JSpinner jSpinnerBiteF;
    private javax.swing.JSpinner jSpinnerBitesC;
    private javax.swing.JSpinner jSpinnerChocolate;
    private javax.swing.JSpinner jSpinnerChurrodog;
    private javax.swing.JSpinner jSpinnerCoffee;
    private javax.swing.JSpinner jSpinnerCoke;
    private javax.swing.JSpinner jSpinnerCrispymania;
    private javax.swing.JSpinner jSpinnerFanta;
    private javax.swing.JSpinner jSpinnerIcecream;
    private javax.swing.JSpinner jSpinnerSprite;
    private javax.swing.JSpinner jSpinnerSundae;
    private javax.swing.JSpinner jSpinnerTwist;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables
}
