/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package final_project;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.*;
import java.io.*;

/**
 *
 * @author kevinsanchez
 */
public class JFrameFrontPage extends javax.swing.JFrame {

    /**
     * Creates new form JFrameFrontPage
     */
    
    public JFrameFrontPage() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jTextFieldLogUser.setVisible(false);
        jPasswordFieldLogIn.setVisible(false);
        jTextFieldSingUser.setVisible(false);
        jPasswordFieldSingUp.setVisible(false);
        jButtonEnter.setVisible(false);
        jButtonRegister.setVisible(false);
        jPanel3.setVisible(false);
        jPanel1.setVisible(false);
  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jButtonSingUp = new javax.swing.JButton();
        jButtonLogIn = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jPasswordFieldSingUp = new javax.swing.JPasswordField();
        jPasswordFieldLogIn = new javax.swing.JPasswordField();
        jTextFieldSingUser = new javax.swing.JTextField();
        jTextFieldLogUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonRegister = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonEnter = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabelTitle.setFont(new java.awt.Font("Chalkduster", 1, 70)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 153, 51));
        jLabelTitle.setText("OrderD");
        jPanel2.add(jLabelTitle);
        jLabelTitle.setBounds(90, 10, 310, 130);

        jButtonSingUp.setBackground(new java.awt.Color(153, 255, 153));
        jButtonSingUp.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jButtonSingUp.setForeground(new java.awt.Color(0, 153, 51));
        jButtonSingUp.setText("Sing up");
        jButtonSingUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSingUpActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSingUp);
        jButtonSingUp.setBounds(410, 190, 97, 29);

        jButtonLogIn.setBackground(new java.awt.Color(153, 255, 153));
        jButtonLogIn.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jButtonLogIn.setForeground(new java.awt.Color(0, 153, 51));
        jButtonLogIn.setText("Log in");
        jButtonLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogInActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonLogIn);
        jButtonLogIn.setBounds(110, 190, 91, 29);

        jButtonClose.setBackground(new java.awt.Color(153, 255, 153));
        jButtonClose.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jButtonClose.setForeground(new java.awt.Color(0, 153, 51));
        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonClose);
        jButtonClose.setBounds(0, 450, 97, 29);

        jPasswordFieldSingUp.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.add(jPasswordFieldSingUp);
        jPasswordFieldSingUp.setBounds(440, 280, 180, 26);

        jPasswordFieldLogIn.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.add(jPasswordFieldLogIn);
        jPasswordFieldLogIn.setBounds(100, 270, 170, 26);

        jTextFieldSingUser.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.add(jTextFieldSingUser);
        jTextFieldSingUser.setBounds(440, 240, 180, 26);

        jTextFieldLogUser.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.add(jTextFieldLogUser);
        jTextFieldLogUser.setBounds(100, 240, 170, 26);

        jLabel5.setText("Create a username:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(320, 250, 130, 16);

        jLabel3.setText("Username:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 250, 70, 16);

        jLabel4.setText("Password:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 280, 70, 16);

        jLabel6.setText("Create a password:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(320, 290, 130, 16);

        jButtonRegister.setBackground(new java.awt.Color(153, 255, 153));
        jButtonRegister.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jButtonRegister.setForeground(new java.awt.Color(0, 153, 51));
        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRegister);
        jButtonRegister.setBounds(410, 320, 104, 29);

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(310, 230, 310, 120);

        jButtonEnter.setBackground(new java.awt.Color(153, 255, 153));
        jButtonEnter.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jButtonEnter.setForeground(new java.awt.Color(0, 153, 51));
        jButtonEnter.setText("Enter");
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEnter);
        jButtonEnter.setBounds(120, 310, 70, 29);

        jPanel3.setBackground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(20, 230, 250, 110);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/Background2.png"))); // NOI18N
        jPanel2.add(jLabelBackground);
        jLabelBackground.setBounds(200, 0, 730, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Good bye", "Closing" ,JOptionPane.PLAIN_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogInActionPerformed
        // TODO add your handling code here:
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jTextFieldLogUser.setVisible(true);
        jPasswordFieldLogIn.setVisible(true);
        jButtonEnter.setVisible(true);
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jButtonLogInActionPerformed

    private void jButtonSingUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSingUpActionPerformed
        // TODO add your handling code here:
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jTextFieldSingUser.setVisible(true);
        jPasswordFieldSingUp.setVisible(true);
        jButtonRegister.setVisible(true);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_jButtonSingUpActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        // TODO add your handling code here:
        String Suser = jTextFieldSingUser.getText();
        String Spassword = String.valueOf(jPasswordFieldSingUp.getPassword());
        
        try{
            FileWriter fileWriter = new FileWriter("AccountsData.txt",true);
            fileWriter.write(Suser + ";" + Spassword + "\n");
            fileWriter.close();
            JOptionPane.showMessageDialog(null, "Your account has been created", "Congratulations" ,JOptionPane.INFORMATION_MESSAGE);
            }
        catch(Exception f){
            System.out.println("Error");   
            }
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
        // TODO add your handling code here:
        String Luser = jTextFieldLogUser.getText();
        String Lpassword = String.valueOf(jPasswordFieldLogIn.getPassword());
       
        File file = new File("AccountsData.txt");
        
        try{
            Scanner scanner = new Scanner(file);
            while(scanner.hasNextLine()){
                String line = scanner.nextLine();
                String [] componets = line.split(";");
                String user = componets[0];
                String passw = componets[1];
                
                if(user.equals(Luser) && passw.equals(Lpassword)){
                    JFrameAccount frameA = new JFrameAccount();
                    frameA.setVisible(true);
                    dispose();
                }
            }

        }catch(Exception t){
            System.out.println("Error");
        }
  
        
    }//GEN-LAST:event_jButtonEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameFrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameFrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameFrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameFrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameFrontPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JButton jButtonLogIn;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonSingUp;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordFieldLogIn;
    private javax.swing.JPasswordField jPasswordFieldSingUp;
    private javax.swing.JTextField jTextFieldLogUser;
    private javax.swing.JTextField jTextFieldSingUser;
    // End of variables declaration//GEN-END:variables
}
