/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package final_project;

import java.awt.Color;
import java.util.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kevinsanchez
 */
public class JFramePolloTropical extends javax.swing.JFrame {

    /**
     * Creates new form JFramePolloTropical
     */
    String nameF;
    String phoneF;
    String addressF;
    String cardnumF;
    String cardexF;
    
    public JFramePolloTropical() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonPickUp = new javax.swing.JRadioButton();
        jSpinnerMacCheese = new javax.swing.JSpinner();
        jSpinnerCorn = new javax.swing.JSpinner();
        jSpinnerTropichop = new javax.swing.JSpinner();
        jSpinnerFanta = new javax.swing.JSpinner();
        jSpinnerYrice = new javax.swing.JSpinner();
        jSpinnerSalad = new javax.swing.JSpinner();
        jSpinnerPlantains = new javax.swing.JSpinner();
        jRadioButtonDelivery = new javax.swing.JRadioButton();
        jSpinnerSprite = new javax.swing.JSpinner();
        jSpinnerWrice = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerTomatoes = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpinnerBeans = new javax.swing.JSpinner();
        jSpinnerCoke = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSpinnerMashedPotato = new javax.swing.JSpinner();
        jButtonClose = new javax.swing.JButton();
        jButtonGoBack = new javax.swing.JButton();
        jButtonMakeOrder = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jRadioButtonPickUp.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jRadioButtonPickUp.setForeground(new java.awt.Color(0, 153, 51));
        jRadioButtonPickUp.setText("Pick up");
        jRadioButtonPickUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPickUpActionPerformed(evt);
            }
        });

        jRadioButtonDelivery.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jRadioButtonDelivery.setForeground(new java.awt.Color(0, 153, 51));
        jRadioButtonDelivery.setText("Delivery");
        jRadioButtonDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDeliveryActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/PolloImages/pollotitle.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/PolloImages/PolloWhiteRice.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/PolloImages/PolloBalsamicTomatoes.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/PolloImages/PolloBlackBeans.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/PolloImages/Coca-Cola.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/PolloImages/PolloYellowRiceWithVegetables.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/PolloImages/PolloCesarSalad.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/PolloImages/PolloSweetPlantains.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/PolloImages/Sprite.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/PolloImages/PolloMac&Cheese.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/PolloImages/PolloKernelCorn.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/PolloImages/PolloTropiChop(GrilledChicken,YellowRice&BlackBeans).png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/PolloImages/FantaOrange.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/PolloImages/PolloMashedPotatoesWithGravy.png"))); // NOI18N

        jButtonClose.setBackground(new java.awt.Color(153, 255, 153));
        jButtonClose.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jButtonClose.setForeground(new java.awt.Color(0, 153, 51));
        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jButtonGoBack.setBackground(new java.awt.Color(153, 255, 153));
        jButtonGoBack.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jButtonGoBack.setForeground(new java.awt.Color(0, 153, 51));
        jButtonGoBack.setText("Go back");
        jButtonGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoBackActionPerformed(evt);
            }
        });

        jButtonMakeOrder.setBackground(new java.awt.Color(153, 255, 153));
        jButtonMakeOrder.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jButtonMakeOrder.setForeground(new java.awt.Color(0, 153, 51));
        jButtonMakeOrder.setText("Make OrderD");
        jButtonMakeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMakeOrderActionPerformed(evt);
            }
        });

        jLabel15.setText("White Rice $3.74");

        jLabel16.setText("Balsamic Tomatoes $3.74");

        jLabel17.setText("Caesar Salad $3.74");

        jLabel18.setText("Kernel Corn $3.74");

        jLabel19.setText("Black Beans $3.74");

        jLabel20.setText("Sweet Plantains $4.99");

        jLabel21.setText("Grilled Chicken Tropichop $8.49");

        jLabel22.setText("Mac & Cheese $3.74");

        jLabel23.setText("Mashed Potatoes $3.74");

        jLabel24.setText("Yellow Rice & Vegetables $3.74 ");

        jLabel25.setText("Coke $1.19");

        jLabel26.setText("Sprite $1.19");

        jLabel27.setText("Fanta Orange $1.19");

        jLabel30.setText("Please confirm your data ");

        jLabel28.setText("Name:");

        jTextFieldName.setBackground(new java.awt.Color(153, 255, 153));

        jTextFieldPhone.setBackground(new java.awt.Color(153, 255, 153));

        jLabel29.setText("Phone:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerWrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(jLabel15))
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerTomatoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerSalad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerCorn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel16)
                .addGap(41, 41, 41)
                .addComponent(jLabel17)
                .addGap(66, 66, 66)
                .addComponent(jLabel18))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerBeans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerPlantains, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel12)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerTropichop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel10)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerMacCheese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel14)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerMashedPotato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel19)
                .addGap(59, 59, 59)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addGap(29, 29, 29)
                .addComponent(jLabel22)
                .addGap(39, 39, 39)
                .addComponent(jLabel23))
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerCoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel9)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerSprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel13)
                .addGap(6, 6, 6)
                .addComponent(jSpinnerFanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel25)
                .addGap(93, 93, 93)
                .addComponent(jLabel26)
                .addGap(87, 87, 87)
                .addComponent(jLabel27)
                .addGap(37, 37, 37)
                .addComponent(jLabel30))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGoBack)
                    .addComponent(jButtonClose))
                .addGap(231, 231, 231)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel6)
                        .addGap(6, 6, 6)
                        .addComponent(jSpinnerYrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel24))
                .addGap(181, 181, 181)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(8, 8, 8)
                        .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(0, 0, 0)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButtonPickUp)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jRadioButtonDelivery))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jButtonMakeOrder))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jSpinnerWrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel15)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jSpinnerTomatoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jSpinnerSalad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jSpinnerCorn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnerBeans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jSpinnerPlantains, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jSpinnerTropichop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jSpinnerMacCheese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jSpinnerMashedPotato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jSpinnerCoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jSpinnerSprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jSpinnerFanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel30)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButtonGoBack)
                        .addGap(1, 1, 1)
                        .addComponent(jButtonClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jSpinnerYrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel28))
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel29))
                            .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonPickUp)
                            .addComponent(jRadioButtonDelivery)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButtonMakeOrder))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoBackActionPerformed
        // TODO add your handling code here:
        JFrameAccount frameA = new JFrameAccount();
        frameA.show();
        dispose();
    }//GEN-LAST:event_jButtonGoBackActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Good bye", "Closing" ,JOptionPane.PLAIN_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonMakeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMakeOrderActionPerformed
        // TODO add your handling code here:
        try{
            
        double wrice = (int)jSpinnerWrice.getValue() * 3.74;
        double tomatoes = (int)jSpinnerTomatoes.getValue() * 3.74;
        double salad = (int)jSpinnerSalad.getValue() * 3.74;
        double corn = (int)jSpinnerCorn.getValue() * 3.74;
        double beans = (int)jSpinnerBeans.getValue() * 3.74;
        double plantains = (int)jSpinnerPlantains.getValue() * 4.99;
        double tropichop = (int)jSpinnerTropichop.getValue() * 8.49;
        double macheese = (int)jSpinnerMacCheese.getValue() * 3.74;
        double mashedpotato = (int)jSpinnerMashedPotato.getValue() * 3.74;
        double coke = (int)jSpinnerCoke.getValue() * 1.19;
        double sprite = (int)jSpinnerSprite.getValue() * 1.19;
        double fanta = (int)jSpinnerFanta.getValue() * 1.19;
        double yrice = (int)jSpinnerYrice.getValue() * 3.74;
        double total = 0;
        double totaltax = 0;
        double salestax = 0;
        String name = jTextFieldName.getText();
        String phone = jTextFieldPhone.getText();
        
        
        Random Order = new Random();
        int ordernum = 99999999 + Order.nextInt(99999999);
        
        File file = new File("OrderData.txt");

            Scanner scanner = new Scanner(file);
            while(scanner.hasNextLine()){
                String line = scanner.nextLine();
                String [] componets = line.split(";");
                String nameData = componets[0];
                String addressData = componets[1];
                String phoneData = componets[2];
                String cardnumData = componets[3];
                String cardexData = componets[4];
                
                if(nameData.equals(name) && phoneData.equals(phone)){
                    nameF = nameData;
                    phoneF = phoneData;
                    addressF = addressData;
                    cardnumF = cardnumData;
                    cardexF = cardexData;
                }
            }
            
           FileWriter fileWriter = new FileWriter("Receipt.txt");
           if(jRadioButtonDelivery.isSelected()){
               fileWriter.write("Thank you for shopping at Pollo Tropical " + nameF + "\n" +
                    "- Your order will be sent to your address: "+ addressF + "\n" + 
                    "- Your order number is #" + ordernum + "\n" + 
                    "- Your debit/credit card used was **** **** **** " + cardnumF.substring(cardnumF.length()-4) + "\n" +
                    "- If there is any problem we will call you on your phone " + phoneF + "\n" + "\n");
           } else{
               fileWriter.write("Thank you for shopping at Pollo Tropical " + nameF + "\n" +
                    "- Your order will be ready to pick up on the closest restaurant to your address: " + addressF + "\n" +
                    "- Your order number is #" + ordernum + "\n" + 
                    "- Your debit/credit card used was **** **** **** " + cardnumF.substring(cardnumF.length()-4) + "\n" +
                    "- If there is any problem we will call you on your phone " + phoneF + "\n" + "\n");
           }
            
        if(wrice>0){
            String wriceF = String.format("%.2f", wrice);
            fileWriter.write(jSpinnerWrice.getValue() + " White Rice: $" + wriceF);
            total += wrice;
        }
        if(tomatoes>0){
            String tomatoesF = String.format("%.2f", tomatoes);
            fileWriter.write(jSpinnerTomatoes.getValue() + " Balsamic Tomatoes: $" + tomatoesF + "\n");
            total += tomatoes;
        }
        if(salad>0){
            String saladF = String.format("%.2f", salad);
            fileWriter.write(jSpinnerSalad.getValue() + " Caesar Salad: $" + saladF + "\n");
            total += salad;
        }
        if(corn>0){
            String cornF = String.format("%.2f", corn);
            fileWriter.write(jSpinnerCorn.getValue() + " Kernel Corn: $" + cornF + "\n");
            total += corn;
        }
        if(beans>0){
            String beansF = String.format("%.2f", beans);
            fileWriter.write(jSpinnerBeans.getValue() + " Black Beans: $" + beansF + "\n");
            total += beans;
        }
        if(plantains>0){
            String plantainsF = String.format("%.2f", plantains);
            fileWriter.write(jSpinnerPlantains.getValue() + " Sweet Plantains: $" + plantainsF + "\n");
            total += plantains;
        }
        if(tropichop>0){
            String tropichopF = String.format("%.2f", tropichop);
            fileWriter.write(jSpinnerTropichop.getValue() + " Regular Tropichop: $" + tropichopF + "\n");
            total += tropichop;
        }
        if(macheese>0){
            String macheeseF = String.format("%.2f", macheese);
            fileWriter.write(jSpinnerMacCheese.getValue() + " Mac & Cheese: $" + macheeseF + "\n");
            total += macheese;
        }
        if(mashedpotato>0){
            String mashedpotatoF = String.format("%.2f", mashedpotato);
            fileWriter.write(jSpinnerMashedPotato.getValue() + " Mashed Potato: $" + mashedpotatoF + "\n");
            total += mashedpotato;
        }
        if(coke>0){
            String cokeF = String.format("%.2f", coke);
            fileWriter.write(jSpinnerCoke.getValue() + " Coke: $" + cokeF + "\n");
            total += coke;
        }
        if(sprite>0){
            String spriteF = String.format("%.2f", sprite);
            fileWriter.write(jSpinnerSprite.getValue() + " Sprite: $" + spriteF + "\n");
            total += sprite;
        }
        if(fanta>0){
            String fantaF = String.format("%.2f", fanta);
            fileWriter.write(jSpinnerFanta.getValue() + " Fanta: $" + fantaF + "\n");
            total += fanta;
        }
        if(yrice>0){
            String yriceF = String.format("%.2f", yrice);
            fileWriter.write(jSpinnerYrice.getValue() + " Yellow Rice: $" + yriceF + "\n");
            total += yrice;
        }
        if(total>0){
            fileWriter.write("\n");
            String totalF = String.format("%.2f", total);
            fileWriter.write("Order Total: " + totalF + "\n");
            
            salestax = total*0.07;
            String salestaxF = String.format("%.2f", salestax);
            fileWriter.write("Sales Tax: $" + salestaxF + "\n");
            
            if(jRadioButtonDelivery.isSelected()){
                totaltax = total + (total * 0.07) + 7.99;
                String totaltaxF = String.format("%.2f", totaltax);
                fileWriter.write("Delivery Fee: +$" + 7.99 + "\n");
                fileWriter.write("Final Total: $" + totaltaxF + "\n");
            } else{
                totaltax = total + (total * 0.07);
                String totaltaxF = String.format("%.2f", totaltax);
                fileWriter.write("Final Total: $" + totaltaxF + "\n");
            }
        }
        fileWriter.close();
        JOptionPane.showMessageDialog(null, "Your order is done, check your receipt", "Congratulations" ,JOptionPane.INFORMATION_MESSAGE);
            }
        
        catch(Exception f){
            JOptionPane.showMessageDialog(null, "Invalid Data!", "System Error" ,JOptionPane.ERROR_MESSAGE);  
            } 
    }//GEN-LAST:event_jButtonMakeOrderActionPerformed

    private void jRadioButtonDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDeliveryActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonDelivery.isSelected()){
            jRadioButtonPickUp.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonDeliveryActionPerformed

    private void jRadioButtonPickUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPickUpActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonPickUp.isSelected()){
            jRadioButtonDelivery.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonPickUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePolloTropical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePolloTropical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePolloTropical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePolloTropical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePolloTropical().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonGoBack;
    private javax.swing.JButton jButtonMakeOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButtonDelivery;
    private javax.swing.JRadioButton jRadioButtonPickUp;
    private javax.swing.JSpinner jSpinnerBeans;
    private javax.swing.JSpinner jSpinnerCoke;
    private javax.swing.JSpinner jSpinnerCorn;
    private javax.swing.JSpinner jSpinnerFanta;
    private javax.swing.JSpinner jSpinnerMacCheese;
    private javax.swing.JSpinner jSpinnerMashedPotato;
    private javax.swing.JSpinner jSpinnerPlantains;
    private javax.swing.JSpinner jSpinnerSalad;
    private javax.swing.JSpinner jSpinnerSprite;
    private javax.swing.JSpinner jSpinnerTomatoes;
    private javax.swing.JSpinner jSpinnerTropichop;
    private javax.swing.JSpinner jSpinnerWrice;
    private javax.swing.JSpinner jSpinnerYrice;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables
}
